# Generated by Django 6.0.5 on 2026-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Введите ID чата в Telegram",
                null=True,
                verbose_name="ID чата в Telegram",
            ),
        ),
    ]
