# Generated by Django 6.0.5 on 2026-06-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите ID чата в Telegram",
                max_length=50,
                null=True,
                verbose_name="ID чата в Telegram",
            ),
        ),
    ]
