# Generated by Django 6.0.5 on 2026-06-18 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("htracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="h_action",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Действие, которое представляет собой привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="h_period",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MaxValueValidator(7)],
                verbose_name="Периодичность привычки в неделю",
            ),
        ),
    ]
