# Generated by Django 6.0.5 on 2026-06-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("htracker", "0002_habit_h_action_alter_habit_h_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
