# Generated by Django 6.0.5 on 2026-06-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("htracker", "0003_habit_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminder_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последнего напоминания"
            ),
        ),
    ]
